export const MATERIALS = {
  'Aceite': { category: 'Líquidos', unit: 'g', unitCost: 0.0565 },
  'Até de guayaba': { category: 'Frutas/Conservas', unit: 'g', unitCost: 0.15 },
  'Azúcar glass LaComer': { category: 'Azúcares', unit: 'g', unitCost: 0.1036 },
  'Azúcar': { category: 'Azúcares', unit: 'g', unitCost: 0.04 },
  'Azúcar Mascabado': { category: 'Azúcares', unit: 'g', unitCost: 0.04 },
  'Bicarbonato de sodio': { category: 'Químicos', unit: 'g', unitCost: 0.1318 },
  'Café soluble': { category: 'Secos', unit: 'g', unitCost: 0.56 },
  'Caja Betty Crocker choc.': { category: 'Premezclas', unit: 'pieza', unitCost: 63 },
  'Caja Pronto naranja': { category: 'Premezclas', unit: 'pieza', unitCost: 60 },
  'Cajeta': { category: 'Lácteos/Conservas', unit: 'g', unitCost: 0.04746 },
  'Canela': { category: 'Especias', unit: 'g', unitCost: 0.6 },
  'Chispas de chocolate': { category: 'Secos', unit: 'g', unitCost: 0.2642 },
  'Coco rallado': { category: 'Frutas/Frutos secos', unit: 'g', unitCost: 0.51 },
  'Cocoa': { category: 'Cacao', unit: 'g', unitCost: 0.55 },
  'Crema batida': { category: 'Lácteos', unit: 'g', unitCost: 0.1255 },
  'Frutos rojos congelados': { category: 'Frutas', unit: 'g', unitCost: 0.1139 },
  'Galletas María': { category: 'Secos', unit: 'g', unitCost: 0.1275 },
  'Grenetina': { category: 'Otros', unit: 'g', unitCost: 0.7486 },
  'Guayaba': { category: 'Frutas', unit: 'pieza', unitCost: 3.0 },
  'Harina': { category: 'Harinas', unit: 'g', unitCost: 0.02 },
  'Huevos': { category: 'Lácteos', unit: 'pieza', unitCost: 3.05 },
  'Jengibre en polvo': { category: 'Especias', unit: 'g', unitCost: 1.12 },
  'Leche': { category: 'Lácteos', unit: 'g', unitCost: 0.033 },
  'Leche condensada': { category: 'Lácteos', unit: 'g', unitCost: 0.0827 },
  'Leche evaporada': { category: 'Lácteos', unit: 'g', unitCost: 0.0694 },
  'Mantequilla': { category: 'Lácteos', unit: 'g', unitCost: 0.1944 },
  'Nuez troceada': { category: 'Frutos secos', unit: 'g', unitCost: 0.3228 },
  'Plátano': { category: 'Frutas', unit: 'pieza', unitCost: 6.0 },
  'Queso crema': { category: 'Lácteos', unit: 'g', unitCost: 0.1755 },
  'Sal': { category: 'Otros', unit: 'g', unitCost: 0.027 },
  'Vainilla': { category: 'Esencias', unit: 'ml', unitCost: 0.0784 },
  'Yogurt griego': { category: 'Lácteos', unit: 'g', unitCost: 0.1093 },
  'Zanahoria rallada': { category: 'Frutas/Vegetales', unit: 'g', unitCost: 0.1029 },
  'Azúcar glass': { category: 'Azúcares', unit: 'g', unitCost: 0.1036 }
};
